### PR TITLE
adding --use_stdout command line argument

### PR DESCRIPTION
**Pull request by brooksandrew**
Hi @rosshamish - Thanks for the great package.

I'm planning to use it for a front-end to collect game information for a Settlers project I'm working on to quantify the each player's "luckiness" (position on their resource collection CDF) at each point in the game.  Sketch of that [here](https://github.com/brooksandrew/catan).  I'd like to run `catan-spectator` as a subprocess:

```python
p = subprocess.Popen(['catan-spectator', '--use_stdout'], stdout=subprocess.PIPE, shell=False)
```

using the `._use_stdout` option on catanlog so I can read game actions as they come in from the Tkinter GUI using something like:

```python
nbsr = NonBlockingStreamReader(p.stdout)
while True:
    output = nbsr.readline(0.1)
    if not output:
        pass
    else:
      # do stuff with output (modify game state, compute stats)
```

which will modify game state on my side, calculate stats and expose them via a Flask API which will be displayed in a separate web based front-end.  

Unless I'm missing something, I don't think I can redirect the catan actions from log to stdout without the feature implemented in this PR, using catan-spectator only.

### CODE REVIEW

**Comment by rosshamish** [comment]
Hey @brooksandrew, thanks for the PR! I like the idea of the catan-karma project. I've got some qualms about the CatanSpectator modifying catanlog's `_use_stdout` property directly (since it's private).

Probably a more future-proof way to implement this would be to pass an argument through the Game constructor into the CatanLog constructor. Though.. that would require modifying both those packages. If you're up for that, I'd say go for it and I can look at both those PRs and publish the new packages. 

Otherwise I'm happy to merge this in as-is.

**Comment by brooksandrew** [comment]
@rosshamish - Sounds good to me.  Still need to test it, but how does this look?  I modified the Game constructor here: https://github.com/rosshamish/catan-py/pull/1

Will let you know when I've confirmed that this works.

**Comment by brooksandrew** [comment]
@rosshamish - Just tested this, successfully.  Also updated the README to reflect the new command line arg.  I'm ready to merge and release if you are.  Thanks for bringing this in!

**Comment by brooksandrew** [comment]
Hi @rosshamish - Just checking in on this.  Saw your thumbs up.  Anything other concerns before merging and cutting a release?

**Comment by rosshamish** [comment]
Sorry -- I got preempted by another task right after thumbs upping and before commenting, and lost this thread. Thanks for pinging it again. No concerns - the change looks good. Thanks for implementing it the "right" way.

**Comment by rosshamish** [comment]
Published 0.1.4! Thanks for the contribution @brooksandrew.

https://pypi.org/project/catan-spectator/#history
image

**Comment by brooksandrew** [comment]
woohoo thanks!

**Pull request merged**
